In [4]:
import numpy as np
import pandas as pd

In [5]:
np.random.seed(0)
# number of jars sold
sales_amount = np.random.randint(20, size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [6]:
# create weekly_sales dataframe
weekly_sales = pd.DataFrame(sales_amount, 
                            index= ["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [8]:
# create price array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [10]:
# create butter_price dataframe
butter_prices = pd.DataFrame(prices.reshape(1,3),
                            index=["Price"],
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [14]:
prices.shape

(3,)

In [15]:
sales_amount.shape

(5, 3)

In [17]:
total_sales = prices.dot(sales_amount.T)
total_sales

array([240, 138, 458, 232, 142])

In [19]:
# create daily_sales
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [21]:
weekly_sales.T.shape

(3, 5)

In [22]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [26]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142